export const Images = {
  mouth: "../src/assets/PNG/icons8-mouth-64.png",
  computer: "../src/assets/PNG/computer.png",
  design: "../src/assets/PNG/design.png",
  marketing: "../src/assets/PNG/web-marketing.png",
  Ahamove: "../src/assets/PNG/Logo-Ahamove.png",
  DownWithAppStore: "../src/assets/PNG/DownWithAppStore.jpg",
  DownWithCHplay: "../src/assets/PNG/DownWithCHplay.jpg",
  bgFooter: "../Images/bgFooter.jpg",
  Advertise: "../src/assets/PNG/Advertise.png",
  unilever: "../src/assets/PNG/unilever.png",
  Puma: "../src/assets/PNG/Puma.png",
  bannerFilter: "../src/assets/Images/bannerFilter.jpg",
  banner: "../src/assets/Images/banner.jpg",
  banner1: "../src/assets/Images/banner1.jpg",
  bgRegisterIcon: "../src/assets/PNG/bgRegisterIcon.png",
  logoSlogan: "../src/assets/PNG/logoSlogan.png",
  logoApple: "../src/assets/PNG/lgApple.png",
  logoGoogle: "../src/assets/PNG/lgG.png",
  logoFace: "../src/assets/PNG/lgFace.png",
  bannerHome: "../src/assets/PNG/Rectangle65.png",
  banerPreeShip: "../src/assets/PNG/banner2.png",
  banner3: "../src/assets/PNG/Rectangle 66.png",
  banner4: "../src/assets/PNG/Rectangle 620.png",
  car: "../src/assets/PNG/car.png",
  headphones: "../src/assets/PNG/headphones.png",
  shopping: "../src/assets/PNG/shopping-bag.png",
  Group: "../src/assets/PNG/Group.png",
  Category1: "../src/assets/PNG/category1.png",
  Category2: "../src/assets/PNG/category2.png",
  Category3: "../src/assets/PNG/category3.png",
  Category4: "../src/assets/PNG/category4.png",
  Category5: "../src/assets/PNG/category5.png",
  Category6: "../src/assets/PNG/category6.png",
  Category7: "../src/assets/PNG/category7.png",
  Category8: "../src/assets/PNG/category8.png",
  Category9: "../src/assets/PNG/category9.png",
  Category10: "../src/assets/PNG/category10.png",
  Category11: "../src/assets/PNG/category11.png",
  Category12: "../src/assets/PNG/category12.png",
  textMom: "../src/assets/PNG/Group 409.png",
  product: "../src/assets/PNG/product.png",
  imgMom1: "../src/assets/PNG/Rectangle 617.png",
  imgMom2: "../src/assets/PNG/Rectangle 618.png",
  imgMom3: "../src/assets/PNG/Rectangle 619.png",
  star1: "../src/assets/PNG/Star 11.png",
  star2: "../src/assets/PNG/Star 15.png",
  flashSale1: "../src/assets/PNG/flashSale1.png",
  chooseUs1: "../src/assets/PNG/chooseUs1.png",
  chooseUs2: "../src/assets/PNG/chooseUs2.png",
  chooseUs3: "../src/assets/PNG/chooseUsCheck.png",
  chooseUs4: "../src/assets/PNG/chooseUsArrow.png",
  puma: "../src/assets/PNG/puma.png",
  spGoiY1: "../src/assets/PNG/spGoiY1.png",
  thuongHieu2: "../src/assets/PNG/thuongHieu2.png",
  adidas: "../src/assets/PNG/adidas.png",
  thuongHieu1: "../src/assets/PNG/thuongHieu1.png",
  hot: "../src/assets/PNG/hot.png",
  picture: "../src/assets/PNG/picture.png",
  avatar_admin: "../../../src/pages/home/admin/assets/Images/avatar.png",
  imageproduct: "../../../src/pages/home/admin/assets/Images/imageproduct.png",
  imageproduct1:
    "../../../src/pages/home/admin/assets/Images/imageproduct1.png",
  imageproduct2:
    "../../../src/pages/home/admin/assets/Images/imageproduct2.png",
  imageproduct3:
    "../../../src/pages/home/admin/assets/Images/imageproduct3.png",
  imageproduct4:
    "../../../src/pages/home/admin/assets/Images/imageproduct4.png",
  imageproduct5:
    "../../../src/pages/home/admin/assets/Images/imageproduct5.png",
  imageproduct6:
    "../../../src/pages/home/admin/assets/Images/imageproduct6.png",
  chevron: "../../../src/pages/home/admin/assets/Images/chevron-right.png",
  chevron1: "../../../src/pages/home/admin/assets/Images/chevron-right1.png",
  Banner: "../src/assets/Images/banner.jpg",
  Banner1: "../src/assets/Images/banner1.jpg",
  BannerQC: "../../../src/pages/home/admin/assets/Images/bannerQC.png",
  imgProduct: "../../../src/pages/home/admin/assets/Images/imgProduct.jpg",
  cateAD: "../src/assets/PNG/cate.png",
  Avtcmt: "../src/assets/Images/Avtcmt.png",
  momo: "../src/assets/PNG/momo.png",
  zalo: "../src/assets/PNG/Logo-ZaloPay.png",
  nhanHang: "../src/assets/PNG/nhanhang.png",
  detailHover: "../src/assets/PNG/Line 56.png",
  visa: "../src/assets/PNG/294654_visa_icon.png",
  EmptyPage: "../src/assets/PNG/Group 863.png",

  viettelpost: "../src/assets/JPG/VTPost.jpg",
  ghn: "../src/assets/PNG/GHN.png",
  bestex: "../src/assets/PNG/bestex.png",
  GHTK: "../src/assets/PNG/GHTK.png",
  ninjavan: "../src/assets/PNG/ninjavan.png",
  JT: "../src/assets/PNG/J&T.png",
  vnpost: "../src/assets/PNG/vnpost.png",
  momo2: "../src/assets/PNG/momo2.png",
  zalopay: "../src/assets/PNG/zalopay.png",

  emptyPages: "../src/assets/PNG/emptyPage.png",
};
